export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MANAGER = 'MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  INBOUND_STAFF = 'INBOUND_STAFF',
  OUTBOUND_STAFF = 'OUTBOUND_STAFF',
  INVENTORY_STAFF = 'INVENTORY_STAFF',
  CASHIER = 'CASHIER',
  AUDITOR = 'AUDITOR',
}

export enum DocumentStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum OfflineActionType {
  CONFIRM_PICK = 'CONFIRM_PICK',
  PUTAWAY_ITEM = 'PUTAWAY_ITEM',
  STOCK_COUNT = 'STOCK_COUNT',
  POS_SALE = 'POS_SALE',
  POS_RETURN = 'POS_RETURN',
  LABEL_PRINT = 'LABEL_PRINT',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCED = 'SYNCED',
  CONFLICT = 'CONFLICT',
  FAILED = 'FAILED',
  DISCARDED = 'DISCARDED',
}
